### ISSUE TITLE
[iOS] non clickable buttons

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/modal#17]
buttons in modals running on iOS are not clickable.

how to reproduce the error:

1. run app in app-tester
2. open login modal
3. fill in credentials
4. press submit

Submit is not clickable but sometimes login succeed anyway without feedback

dependencies:

* `vigour-play#develop` - (`#2ed746d0113b9401044d2069a1a39cd9cb3dfaf8`)
* `vigour-modal@1.0.2`
* `vigour-api@3.0.4`

**Comment by youzi** [comment]
@ninjatux Should be resolved when updating to `vigour-element@1.4.4`

**Comment by ninjatux** [comment]
@youzi now buttons are clickable even if in *transparent* state (form not valid)

![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/249611/13813076/c142eb40-eb7f-11e5-9ca0-245f762f4255.jpeg)

![slack for ios upload png](https://cloud.githubusercontent.com/assets/249611/13813075/c140a6fa-eb7f-11e5-923e-287e97b2f172.jpeg)

**Comment by jimdebeer** [comment]
I know what this is
disabled attribute not working on ios
we need to check on click in the button to fix this

**Comment by youzi** [comment]
@ninjatux I guess this is http://stackoverflow.com/questions/19647638/ios-safari-button-disabled-button-doesnt-disable.

**Comment by jimdebeer** [comment]
fixed disabled state (another issues)
https://github.com/vigour-io/modal/commit/7a6200fdc4da9de467764b0ce3194b29b426020f
