### ISSUE TITLE
`cursor: hand` on non-clickable elements

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/modal#2]
_From @shawninder on March 5, 2016 21:16_

The input fields in the login and register modals display a validation icon (a checkmark or a cross) to the right of the content. These are not clickable, but hovering them with the mouse turns it into a hand. The hand cursor should be reserved for clickable elements. Another place I've noticed the hand appearing over a non-clickable element is in notifications. Only the cross is clickable but hovering produces a hand cursor over the entirety of the notification

Jim says:

> needs user-select: none
> and cursor: default or something

_Copied from original issue: vigour-io/play#128_

**Comment by jimdebeer** [comment]
_From @shawninder on March 5, 2016 21:18_

Hmm, actually clicking these icons provides focus to that input field. I hadn't noticed because that  focus field already had focus the first time I tried... So they behave the same way as the icons on the left. Not sure what to think here

**Comment by nikoloza** [comment]
The whole thing is label and clicking on there will focus any kind of form element inside. That's why it has pointer cursor. Closing.
